export const ADD_NEW_CLASS = 'ADD_NEW_CLASS';
export const DELETE_CLASS = 'DELETE_CLASS';
export const POST_LOGIN = 'POST_LOGIN';
export const DID_LOGIN_ACTION = 'DID_LOGIN_ACTION';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';

export const GET_ALL_COURSE = 'GET_ALL_COURSES';
export const GET_COURSE_SUCCESS = 'GET_COURSE_SUCCESS';
export const GET_COURSE_ERROR = 'GET_COURSE_ERROR';

export const GET_BUILDING = 'GET_BUILDING';
export const GET_BUILDING_SUCCESS = 'GET_BUILDING_SUCCESS';
export const GET_BUILDING_ERROR = 'GET_BUILDING_ERROR';
